### ISSUE TITLE
World creater does not have builder role

### ISSUE THREAD

**Issue by Schuwi** [Trichtern/BuildSystem#127]
### Steps to reproduce

1. Play as a user with permissions `buildsystem.create.private` and `buildsystem.create.private.1`.
2. Create a private world.
3. Try to use worldedit commands.
4. Observe the commands failing.

### What is expected?

The creator of a (private) world should always have build permissions or be added as builder automatically on creation.

### What is actually happening?

Users creating a private word do not have permission to use building commands on their own world. They need to be added as a builder to the world manually.

### Server Info

```shell
Minecraft version: 1.19
Paper version: git-Paper-94
BuildSystem version: 2.20.5
```

**Comment by Trichtern** [comment]
Is the config option `creator-is-builder` enabled?

**Comment by Schuwi** [comment]
🤦‍♂️ It was not. Thank you!
