### ISSUE TITLE
Clear Inventory error

### ISSUE THREAD

**Issue by TWME-TW** [Trichtern/BuildSystem#146]
### Steps to reproduce

Not sure yet (under testing), it seems that there will be an error after turn on Clear Inventory?

### What is expected?

No error 

### What is actually happening?

Some error messages appear in the console

https://paste.gg/p/anonymous/d210fe80f0864e3b9e4b713988be7c0a

### Server Info

```shell
Plugins version: 2.21.2
Server version: Purpur-1825 (MC: 1.19.2)
```

### Any additional comments?

When updating plugin translations

**Comment by Trichtern** [comment]
Can't reproduce.

Turning on Clear Inventory should have nothing to do with what the log says.
For some reason a world is null and therefore a `java.lang.NullPointerException` is thrown. Was a world deleted while you had the inventory open?

And are you using a custom language file? If so can you send it to me?

**Comment by TWME-TW** [comment]
> Can't reproduce.
> 
> Turning on Clear Inventory should have nothing to do with what the log says. For some reason a world is null and therefore a `java.lang.NullPointerException` is thrown. Was a world deleted while you had the inventory open?
> 
> And are you using a custom language file? If so can you send it to me?

I'll keep testing the test when I have time, try to reproduce

https://cdn.discordapp.com/attachments/695635467973951539/1041852293051596951/messages_3.yml

Currently still in translation, latest version:
https://github.com/TWME-TW/twme_translate/blob/main/BuildSystem/messages_new.yml

**Comment by TWME-TW** [comment]
Maybe I mistranslated?  I will try with the English version

**Comment by TWME-TW** [comment]
I can't reproduce either
