### ISSUE TITLE
Unable to import any world

### ISSUE THREAD

**Issue by TWME-TW** [Trichtern/BuildSystem#147]
### Steps to reproduce

unimport the world and re-import, the world won't be imported

### What is expected?

can import the world

### What is actually happening?

unable to import world
https://paste.gg/p/anonymous/3c66396d568d4e05946ee7cc6cce22a5

### Server Info

```shell
Plugins version: 2.21.2
Server version: Purpur-1825 (MC: 1.19.2)
```

**Comment by Trichtern** [comment]
Cannot reproduce, works fine for me.

I un-imported a world and then re-imported the name one and had no issues

Server Info
```
This server is running Pufferfish version git-Pufferfish-42 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: dda277a on HEAD)
You are on the latest version!
```

**Comment by TWME-TW** [comment]
![image](https://user-images.githubusercontent.com/65117253/201796886-b75a7771-3534-45ed-9ae7-ce451be77e46.png)
seems to be working

**Comment by TWME-TW** [comment]
But error
https://paste.gg/p/anonymous/3ab616a5f7994c16a5ea5680366a78cc

**Comment by TWME-TW** [comment]
I'm not sure if this is a bug, but when you copy a world, and import it, it will show the following message
![image](https://user-images.githubusercontent.com/65117253/201808118-de55a7f0-e46c-4bb4-aa31-04c8a5653d68.png)

**Comment by TWME-TW** [comment]
Is it because of this?

config.yml
```
  import-all:
    delay: 30
```

Although I use `/import <world>`

**Comment by TWME-TW** [comment]
Or you have to wait for `Tab command auto-completion` before you can import the world (wait until the world file is scanned?)

**Comment by TWME-TW** [comment]
I'm trying to reproduce the bug on another BuildSystem plugin buyer's server, but obviously not very successful...

I think this should be another problem

**Comment by TWME-TW** [comment]
Closed because I can't determine why

**Comment by Trichtern** [comment]
Maybe something misconfigured? If you ever find a reliable way to reproduce the error, feel free to reopen this
