### ISSUE TITLE
Instant Place Signs do not support mangrove_sign

### ISSUE THREAD

**Issue by TWME-TW** [Trichtern/BuildSystem#150]
### Steps to reproduce

1.Turn on **Instant Place Signs**
2.Place mangrove_sign

### What is expected?

Place a sign without opening a text input.

### What is actually happening?

The text input still appears when the sign is placed.

### Server Info

```shell
git-Paper-279 (MC: 1.19.2)
```

### Any additional comments?

nope

**Comment by Trichtern** [comment]
Waiting for https://github.com/CryptoMorin/XSeries/issues/195 to be resolved
