### ISSUE TITLE
Download worlds from the internet (`/worlds upload`)

### ISSUE THREAD

**Issue by TWME-TW** [Trichtern/BuildSystem#38]
**Command:** `/worlds upload <url>`
- Downloads and then uploads a world from the internet to the server itself.
- File format must be `mca` files or a `ZIP`

**Configurable values:**
- `max-file-size`: The max file size the **entire** file will have (can also be set to `-1` = no limit)
- `whitelisted-urls`: Only urls that are from the following site can be download

**Comment by einTosti** [comment]
I don't know if that is that easy to implement, as the plugin (and especially its source code) is public for the world to see.
Therefore,  I cannot use any auth-keys which make sure **only the plugin** is allowed to upload files to a server.

**Comment by EinJOJO** [comment]
Maybe generate an auth-key by using a private key which can be set in a config?

**Comment by TWME-TW** [comment]
Maybe my meaning is incorrect... I mean downloading to the server

For example, Imageonmap can upload images to the server. Is it possible to upload the map to the server?

（Google translate😬

**Comment by einTosti** [comment]
Ahh, I think I understand you know. 
You're saying that a world file is already uploaded and you want to download it to the server via BuildSystem?

**Comment by TWME-TW** [comment]
Yes

**Comment by EinJOJO** [comment]
That's actually a cool idea!
 
Furthermore, Did you know that FAWE has also a function like that?
You can select an area, copy it and then download it with //download.

But, Before that, you have to setup a webserver.

I just wanted to have said it.

**Comment by TWME-TW** [comment]
I know, but .schem can’t store everything

**Comment by TWME-TW** [comment]
I think of a better analogy: like the wget command of Linux

**Comment by einTosti** [comment]
I updated your proposal. It that the way you want it added?

**Comment by TWME-TW** [comment]
> 我更新了你的建議。它是您想要添加的方式嗎？

(I don't quite understand what you mean, because my bad English

But it occurred to me that maybe after downloading/unzipping, maybe I have to delete the datapacks(.mcmeta) inside the world first?

**Comment by einTosti** [comment]
I can do the following:
1. `/world download <URL>`: Uploads Downloads a world from the internet to the server itself.
2. If the file is a zip, unzip the file

**Comment by TWME-TW** [comment]
> I can do the following:
> 
> 1. `/world download <URL>`: Uploads Downloads a world from the internet to the server itself.
> 2. If the file is a zip, unzip the file

I think yes, that's what I mean

**Comment by TWME-TW** [comment]
I thought about a few possible questions, such as: Will the downloaded file size limit the file to have a bunch of non-map-related data due to decompression? And interfere with the server (such as the emergence of a world called plugins) .Or Zip bomb. And whether it supports some mainstream cloud drives, such as google drive/DropBox/Onedrive.or URL whitelist.

I think this function is powerful, but there may be some unknown problems.

Will this be too difficult?
If it's too difficult, maybe it's time to drop the feature?

**Comment by einTosti** [comment]
I think I would add the following options to the config:
- `max-file-size`: The max file size the **entire** file will have (can also be set to `-1` = no limit)
- `whitelisted-urls`: Only urls that are from the following site can be download

Does that solve any problems?

**Comment by TWME-TW** [comment]
> I think I would add the following options to the config:
> 
> * `max-file-size`: The max file size the **entire** file will have (can also be set to `-1` = no limit)
> * `whitelisted-urls`: Only urls that are from the following site can be download
> 
> Does that solve any problems?

i think yes

**Comment by TWME-TW** [comment]
I don't think this is what this plugin needs right now, maybe I'll try to do it in the future
