### ISSUE TITLE
Permission refinement

### ISSUE THREAD

**Issue by TWME-TW** [Trichtern/BuildSystem#72]
# **Permission refinement**

 Defaults to `.self` when no suffix (`.self`, `.other`)
 like `buildsystem.day` = `buildsystem.day.self`
### `/day [world]`
> `buildsystem.day.self`
> `buildsystem.day.other`

### `/explosions [world]`
> `buildsystem.explosions.self`
> `buildsystem.explosions.other`

### `/night [world]`
> `buildsystem.night.self`
> `buildsystem.night.other`

### `/noai [world]`
> `buildsystem.noai.self`
> `buildsystem.noai.other`

### `/physics [world]`
> `buildsystem.physics.self`
> `buildsystem.physics.other`

### `/worlds addBuilder <world>`
> `buildsystem.addbuilder.self`
> `buildsystem.addbuilder.other`

### `/worlds delete <world>`
> `buildsystem.delete.self`
> `buildsystem.delete.other`

### `/worlds edit <world>`
> `buildsystem.edit.self`
> `buildsystem.edit.other`

### `/worlds info [world]`
> `buildsystem.info.self`
> `buildsystem.info.other`

### `/worlds rename <world>`
> `buildsystem.rename.self`
> `buildsystem.rename.other`

### `/worlds setItem <world>`
> `buildsystem.setitem.self`
> `buildsystem.setitem.other`

### `/worlds setCreator <world>`
> `buildsystem.setcreator.self`
> `buildsystem.setcreator.other`

### `/worlds setProject <world>`
> `buildsystem.setproject.self`
> `buildsystem.setproject.other`

### `/worlds setStatus <world>`
> `buildsystem.setstatus.self`
> `buildsystem.setstatus.other`

### `/worlds setPermission <world>`
> `buildsystem.setpermission.self`
> `buildsystem.setpermission.other`

**Comment by TWME-TW** [comment]
I think this function is quite important, or is there another solution?

**Comment by einTosti** [comment]
I agree that only creators (or admins with the Bypass permission) should be able to make big changes to the world.
However, I’m currently on vacation for the next 10 days so it’ll take a while to implement

**Comment by TWME-TW** [comment]
https://discord.com/channels/419460301403193344/605711763870056448/953366559554945086
`/worlds tp <world>`

`buildsystem.worldtp.builder`
`buildsystem.worldtp.owner`
maybe a good idea？

**Comment by TWME-TW** [comment]
~~Maybe the owner can set whether to allow only builders in
(low priority~~

**Comment by Trichtern** [comment]
Implemented in v2.19
